// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: newsletter_subscription.
// - Entity ID: 102019afbb8d7be79c99b3545b72cba62b4.
// - Entity Version: 102019b00c611587c8c865eed01327fc316.
// - Task ID: 69377e0a9be314c23511c3e0.
// - Task Root ID: 6935e04198d99bdd07fe5953.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for NewsletterSubscriptionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface NewsletterSubscriptionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  email: string;
  discord_username?: string | null;
}

/**
 * ORM class for NewsletterSubscription entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class NewsletterSubscriptionORM {
  private static instance: NewsletterSubscriptionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019afbb8d7be79c99b3545b72cba62b4';
    this.entityName = 'newsletter_subscription';
    this.entityVersion = '102019b00c611587c8c865eed01327fc316';
    this.taskId = '69377e0a9be314c23511c3e0';
    this.taskRootId = '6935e04198d99bdd07fe5953';
  }

  /**
   * Get singleton instance of NewsletterSubscriptionORM
   */
  public static getInstance(): NewsletterSubscriptionORM {
    if (!NewsletterSubscriptionORM.instance) {
      NewsletterSubscriptionORM.instance = new NewsletterSubscriptionORM();
    }
    
    return NewsletterSubscriptionORM.instance;
  }

  /**
   * Get all NewsletterSubscription records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllNewsletterSubscription(): Promise<NewsletterSubscriptionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new NewsletterSubscription record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertNewsletterSubscription(data: NewsletterSubscriptionModel[]): Promise<NewsletterSubscriptionModel[]> {
    const structured = data.map((item) => CreateData(NewsletterSubscriptionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all NewsletterSubscription records
   */
  async purgeAllNewsletterSubscription(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List NewsletterSubscription records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listNewsletterSubscription(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[NewsletterSubscriptionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get newsletter_subscription by Id index
   * This function gets data by index.
   */
  async getNewsletterSubscriptionById(
    id: string,
  ): Promise<NewsletterSubscriptionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) newsletter_subscription by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNewsletterSubscriptionById(
    id: string,
    data: NewsletterSubscriptionModel
  ): Promise<NewsletterSubscriptionModel[]> {
    const index = createIndexId(
      id
    );

    const values = NewsletterSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete newsletter_subscription by Id index
   */
  async deleteNewsletterSubscriptionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get newsletter_subscription by Email index
   * This function gets data by index.
   */
  async getNewsletterSubscriptionByEmail(
    email: string,
  ): Promise<NewsletterSubscriptionModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) newsletter_subscription by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNewsletterSubscriptionByEmail(
    email: string,
    data: NewsletterSubscriptionModel
  ): Promise<NewsletterSubscriptionModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = NewsletterSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete newsletter_subscription by Email index
   */
  async deleteNewsletterSubscriptionByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get newsletter_subscription by DataCreator index
   * This function gets data by index.
   */
  async getNewsletterSubscriptionByDataCreator(
    data_creator: string,
  ): Promise<NewsletterSubscriptionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) newsletter_subscription by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNewsletterSubscriptionByDataCreator(
    data_creator: string,
    data: NewsletterSubscriptionModel
  ): Promise<NewsletterSubscriptionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = NewsletterSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete newsletter_subscription by DataCreator index
   */
  async deleteNewsletterSubscriptionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get newsletter_subscription by DataUpdater index
   * This function gets data by index.
   */
  async getNewsletterSubscriptionByDataUpdater(
    data_updater: string,
  ): Promise<NewsletterSubscriptionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) newsletter_subscription by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setNewsletterSubscriptionByDataUpdater(
    data_updater: string,
    data: NewsletterSubscriptionModel
  ): Promise<NewsletterSubscriptionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = NewsletterSubscriptionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete newsletter_subscription by DataUpdater index
   */
  async deleteNewsletterSubscriptionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to NewsletterSubscriptionModel data array
   */
  private resultToData(values: Data[]): NewsletterSubscriptionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return NewsletterSubscriptionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as NewsletterSubscriptionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized NewsletterSubscriptionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is NewsletterSubscriptionModel => item !== null);
  }
}

/**
 * Convert NewsletterSubscriptionModel data to Value array
 */
function NewsletterSubscriptionModelToValues(data: NewsletterSubscriptionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'discord_username', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof NewsletterSubscriptionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to NewsletterSubscriptionModel data
 */
function NewsletterSubscriptionModelFromValues(values: Value[]): NewsletterSubscriptionModel {
  const data: Partial<NewsletterSubscriptionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'discord_username':
        data.discord_username = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as NewsletterSubscriptionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default NewsletterSubscriptionORM;