// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: press_kit_asset.
// - Entity ID: 102019afbb8d7be7b2387c97b0ac671d872.
// - Entity Version: 102019b00c611587c8c865eed01327fc316.
// - Task ID: 69377e0a9be314c23511c3e0.
// - Task Root ID: 6935e04198d99bdd07fe5953.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for PressKitAssetAssetType
 */
export enum PressKitAssetAssetType {
  Unspecified = 0,
  Logo = 1,
  Screenshot = 2,
  Trailer = 3,
  Artwork = 4,
}



/**
 * Interface for PressKitAssetModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface PressKitAssetModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  asset_name: string;
  description?: string | null;
  file_url: string;
  asset_type: PressKitAssetAssetType;
  file_size: number;
}

/**
 * ORM class for PressKitAsset entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class PressKitAssetORM {
  private static instance: PressKitAssetORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019afbb8d7be7b2387c97b0ac671d872';
    this.entityName = 'press_kit_asset';
    this.entityVersion = '102019b00c611587c8c865eed01327fc316';
    this.taskId = '69377e0a9be314c23511c3e0';
    this.taskRootId = '6935e04198d99bdd07fe5953';
  }

  /**
   * Get singleton instance of PressKitAssetORM
   */
  public static getInstance(): PressKitAssetORM {
    if (!PressKitAssetORM.instance) {
      PressKitAssetORM.instance = new PressKitAssetORM();
    }
    
    return PressKitAssetORM.instance;
  }

  /**
   * Get all PressKitAsset records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllPressKitAsset(): Promise<PressKitAssetModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new PressKitAsset record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertPressKitAsset(data: PressKitAssetModel[]): Promise<PressKitAssetModel[]> {
    const structured = data.map((item) => CreateData(PressKitAssetModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all PressKitAsset records
   */
  async purgeAllPressKitAsset(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List PressKitAsset records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listPressKitAsset(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[PressKitAssetModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get press_kit_asset by Id index
   * This function gets data by index.
   */
  async getPressKitAssetById(
    id: string,
  ): Promise<PressKitAssetModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) press_kit_asset by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPressKitAssetById(
    id: string,
    data: PressKitAssetModel
  ): Promise<PressKitAssetModel[]> {
    const index = createIndexId(
      id
    );

    const values = PressKitAssetModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete press_kit_asset by Id index
   */
  async deletePressKitAssetById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get press_kit_asset by AssetType index
   * This function gets data by index.
   */
  async getPressKitAssetByAssetType(
    asset_type: PressKitAssetAssetType,
  ): Promise<PressKitAssetModel[]> {
    const index = createIndexAssetType(
      asset_type
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) press_kit_asset by AssetType index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPressKitAssetByAssetType(
    asset_type: PressKitAssetAssetType,
    data: PressKitAssetModel
  ): Promise<PressKitAssetModel[]> {
    const index = createIndexAssetType(
      asset_type
    );

    const values = PressKitAssetModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete press_kit_asset by AssetType index
   */
  async deletePressKitAssetByAssetType(
    asset_type: PressKitAssetAssetType
  ): Promise<void> {
    const index = createIndexAssetType(
      asset_type
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get press_kit_asset by DataCreator index
   * This function gets data by index.
   */
  async getPressKitAssetByDataCreator(
    data_creator: string,
  ): Promise<PressKitAssetModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) press_kit_asset by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPressKitAssetByDataCreator(
    data_creator: string,
    data: PressKitAssetModel
  ): Promise<PressKitAssetModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = PressKitAssetModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete press_kit_asset by DataCreator index
   */
  async deletePressKitAssetByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get press_kit_asset by DataUpdater index
   * This function gets data by index.
   */
  async getPressKitAssetByDataUpdater(
    data_updater: string,
  ): Promise<PressKitAssetModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) press_kit_asset by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setPressKitAssetByDataUpdater(
    data_updater: string,
    data: PressKitAssetModel
  ): Promise<PressKitAssetModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = PressKitAssetModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete press_kit_asset by DataUpdater index
   */
  async deletePressKitAssetByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to PressKitAssetModel data array
   */
  private resultToData(values: Data[]): PressKitAssetModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return PressKitAssetModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as PressKitAssetModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized PressKitAssetModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is PressKitAssetModel => item !== null);
  }
}

/**
 * Convert PressKitAssetModel data to Value array
 */
function PressKitAssetModelToValues(data: PressKitAssetModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'asset_name', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'file_url', type: DataType.string, defaultValue: '' },
    { key: 'asset_type', type: DataType.enumeration, defaultValue: 0 },
    { key: 'file_size', type: DataType.number, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof PressKitAssetModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to PressKitAssetModel data
 */
function PressKitAssetModelFromValues(values: Value[]): PressKitAssetModel {
  const data: Partial<PressKitAssetModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'asset_name':
        data.asset_name = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'file_url':
        data.file_url = ParseValue(value, DataType.string) as string;
        break;
      case 'asset_type':
        data.asset_type = ParseValue(value, DataType.enumeration) as PressKitAssetAssetType;
        break;
      case 'file_size':
        data.file_size = ParseValue(value, DataType.number) as number;
        break;
    }
  }
  
  return data as PressKitAssetModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for AssetType fields
 */
function createIndexAssetType(
  asset_type: PressKitAssetAssetType
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, asset_type, 'asset_type'),
  ];

  return {
    fields: ['asset_type'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default PressKitAssetORM;