// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: game.
// - Entity ID: 102019afbb8d7be746c982a34d598073227.
// - Entity Version: 102019b00c611587c8c865eed01327fc316.
// - Task ID: 69377e0a9be314c23511c3e0.
// - Task Root ID: 6935e04198d99bdd07fe5953.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for GameStatus
 */
export enum GameStatus {
  Unspecified = 0,
  ComingSoon = 1,
  Released = 2,
  InDevelopment = 3,
}



/**
 * Interface for GameModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface GameModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  title: string;
  short_description: string;
  long_description?: string | null;
  category: string;
  status: GameStatus;
  cover_image: string;
  screenshots?: string[] | null;
  tags?: string[] | null;
  steam_link?: string | null;
  wishlist_link?: string | null;
  is_hidden?: boolean | null;
  display_order?: number | null;
}

/**
 * ORM class for Game entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class GameORM {
  private static instance: GameORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019afbb8d7be746c982a34d598073227';
    this.entityName = 'game';
    this.entityVersion = '102019b00c611587c8c865eed01327fc316';
    this.taskId = '69377e0a9be314c23511c3e0';
    this.taskRootId = '6935e04198d99bdd07fe5953';
  }

  /**
   * Get singleton instance of GameORM
   */
  public static getInstance(): GameORM {
    if (!GameORM.instance) {
      GameORM.instance = new GameORM();
    }
    
    return GameORM.instance;
  }

  /**
   * Get all Game records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllGame(): Promise<GameModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new Game record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertGame(data: GameModel[]): Promise<GameModel[]> {
    const structured = data.map((item) => CreateData(GameModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all Game records
   */
  async purgeAllGame(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List Game records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listGame(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[GameModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get game by Id index
   * This function gets data by index.
   */
  async getGameById(
    id: string,
  ): Promise<GameModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameById(
    id: string,
    data: GameModel
  ): Promise<GameModel[]> {
    const index = createIndexId(
      id
    );

    const values = GameModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game by Id index
   */
  async deleteGameById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game by Status index
   * This function gets data by index.
   */
  async getGameByStatus(
    status: GameStatus,
  ): Promise<GameModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameByStatus(
    status: GameStatus,
    data: GameModel
  ): Promise<GameModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = GameModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game by Status index
   */
  async deleteGameByStatus(
    status: GameStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game by Category index
   * This function gets data by index.
   */
  async getGameByCategory(
    category: string,
  ): Promise<GameModel[]> {
    const index = createIndexCategory(
      category
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game by Category index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameByCategory(
    category: string,
    data: GameModel
  ): Promise<GameModel[]> {
    const index = createIndexCategory(
      category
    );

    const values = GameModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game by Category index
   */
  async deleteGameByCategory(
    category: string
  ): Promise<void> {
    const index = createIndexCategory(
      category
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game by IsHidden index
   * This function gets data by index.
   */
  async getGameByIsHidden(
    is_hidden: boolean,
  ): Promise<GameModel[]> {
    const index = createIndexIsHidden(
      is_hidden
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game by IsHidden index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameByIsHidden(
    is_hidden: boolean,
    data: GameModel
  ): Promise<GameModel[]> {
    const index = createIndexIsHidden(
      is_hidden
    );

    const values = GameModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game by IsHidden index
   */
  async deleteGameByIsHidden(
    is_hidden: boolean
  ): Promise<void> {
    const index = createIndexIsHidden(
      is_hidden
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game by DisplayOrder index
   * This function gets data by index.
   */
  async getGameByDisplayOrder(
    display_order: number,
  ): Promise<GameModel[]> {
    const index = createIndexDisplayOrder(
      display_order
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game by DisplayOrder index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameByDisplayOrder(
    display_order: number,
    data: GameModel
  ): Promise<GameModel[]> {
    const index = createIndexDisplayOrder(
      display_order
    );

    const values = GameModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game by DisplayOrder index
   */
  async deleteGameByDisplayOrder(
    display_order: number
  ): Promise<void> {
    const index = createIndexDisplayOrder(
      display_order
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game by DataCreator index
   * This function gets data by index.
   */
  async getGameByDataCreator(
    data_creator: string,
  ): Promise<GameModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameByDataCreator(
    data_creator: string,
    data: GameModel
  ): Promise<GameModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = GameModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game by DataCreator index
   */
  async deleteGameByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game by DataUpdater index
   * This function gets data by index.
   */
  async getGameByDataUpdater(
    data_updater: string,
  ): Promise<GameModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameByDataUpdater(
    data_updater: string,
    data: GameModel
  ): Promise<GameModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = GameModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game by DataUpdater index
   */
  async deleteGameByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to GameModel data array
   */
  private resultToData(values: Data[]): GameModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return GameModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as GameModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized GameModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is GameModel => item !== null);
  }
}

/**
 * Convert GameModel data to Value array
 */
function GameModelToValues(data: GameModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'short_description', type: DataType.string, defaultValue: '' },
    { key: 'long_description', type: DataType.string, defaultValue: null },
    { key: 'category', type: DataType.string, defaultValue: '' },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'cover_image', type: DataType.string, defaultValue: '' },
    { key: 'screenshots', type: DataType.array, defaultValue: null },
    { key: 'tags', type: DataType.array, defaultValue: null },
    { key: 'steam_link', type: DataType.string, defaultValue: null },
    { key: 'wishlist_link', type: DataType.string, defaultValue: null },
    { key: 'is_hidden', type: DataType.boolean, defaultValue: null },
    { key: 'display_order', type: DataType.number, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof GameModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to GameModel data
 */
function GameModelFromValues(values: Value[]): GameModel {
  const data: Partial<GameModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'short_description':
        data.short_description = ParseValue(value, DataType.string) as string;
        break;
      case 'long_description':
        data.long_description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'category':
        data.category = ParseValue(value, DataType.string) as string;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as GameStatus;
        break;
      case 'cover_image':
        data.cover_image = ParseValue(value, DataType.string) as string;
        break;
      case 'screenshots':
        data.screenshots = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'tags':
        data.tags = ParseValue(value, DataType.array) as string[] | null;
        break;
      case 'steam_link':
        data.steam_link = ParseValue(value, DataType.string) as string | null;
        break;
      case 'wishlist_link':
        data.wishlist_link = ParseValue(value, DataType.string) as string | null;
        break;
      case 'is_hidden':
        data.is_hidden = ParseValue(value, DataType.boolean) as boolean | null;
        break;
      case 'display_order':
        data.display_order = ParseValue(value, DataType.number) as number | null;
        break;
    }
  }
  
  return data as GameModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: GameStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for Category fields
 */
function createIndexCategory(
  category: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, category, 'category'),
  ];

  return {
    fields: ['category'],
    values
  };
}
/**
 * Create index for IsHidden fields
 */
function createIndexIsHidden(
  is_hidden: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_hidden, 'is_hidden'),
  ];

  return {
    fields: ['is_hidden'],
    values
  };
}
/**
 * Create index for DisplayOrder fields
 */
function createIndexDisplayOrder(
  display_order: number
): Index {
  const values: Value[] = [
    CreateValue(DataType.number, display_order, 'display_order'),
  ];

  return {
    fields: ['display_order'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default GameORM;