// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: admin_user.
// - Entity ID: 102019afbb8d7be7f078964f9197201086a.
// - Entity Version: 102019b00c611587c8c865eed01327fc316.
// - Task ID: 69377e0a9be314c23511c3e0.
// - Task Root ID: 6935e04198d99bdd07fe5953.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for AdminUserRole
 */
export enum AdminUserRole {
  Unspecified = 0,
  SuperAdmin = 1,
  Admin = 2,
  Moderator = 3,
}
/**
 * Enumeration for AdminUserStatus
 */
export enum AdminUserStatus {
  Unspecified = 0,
  Active = 1,
  Suspended = 2,
  Inactive = 3,
}



/**
 * Interface for AdminUserModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface AdminUserModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  username: string;
  email: string;
  password_hash: string;
  role: AdminUserRole;
  status: AdminUserStatus;
  last_login?: string | null;
}

/**
 * ORM class for AdminUser entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class AdminUserORM {
  private static instance: AdminUserORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019afbb8d7be7f078964f9197201086a';
    this.entityName = 'admin_user';
    this.entityVersion = '102019b00c611587c8c865eed01327fc316';
    this.taskId = '69377e0a9be314c23511c3e0';
    this.taskRootId = '6935e04198d99bdd07fe5953';
  }

  /**
   * Get singleton instance of AdminUserORM
   */
  public static getInstance(): AdminUserORM {
    if (!AdminUserORM.instance) {
      AdminUserORM.instance = new AdminUserORM();
    }
    
    return AdminUserORM.instance;
  }

  /**
   * Get all AdminUser records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllAdminUser(): Promise<AdminUserModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new AdminUser record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertAdminUser(data: AdminUserModel[]): Promise<AdminUserModel[]> {
    const structured = data.map((item) => CreateData(AdminUserModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all AdminUser records
   */
  async purgeAllAdminUser(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List AdminUser records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listAdminUser(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[AdminUserModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get admin_user by Id index
   * This function gets data by index.
   */
  async getAdminUserById(
    id: string,
  ): Promise<AdminUserModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_user by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminUserById(
    id: string,
    data: AdminUserModel
  ): Promise<AdminUserModel[]> {
    const index = createIndexId(
      id
    );

    const values = AdminUserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_user by Id index
   */
  async deleteAdminUserById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_user by Username index
   * This function gets data by index.
   */
  async getAdminUserByUsername(
    username: string,
  ): Promise<AdminUserModel[]> {
    const index = createIndexUsername(
      username
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_user by Username index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminUserByUsername(
    username: string,
    data: AdminUserModel
  ): Promise<AdminUserModel[]> {
    const index = createIndexUsername(
      username
    );

    const values = AdminUserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_user by Username index
   */
  async deleteAdminUserByUsername(
    username: string
  ): Promise<void> {
    const index = createIndexUsername(
      username
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_user by Email index
   * This function gets data by index.
   */
  async getAdminUserByEmail(
    email: string,
  ): Promise<AdminUserModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_user by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminUserByEmail(
    email: string,
    data: AdminUserModel
  ): Promise<AdminUserModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = AdminUserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_user by Email index
   */
  async deleteAdminUserByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_user by Role index
   * This function gets data by index.
   */
  async getAdminUserByRole(
    role: AdminUserRole,
  ): Promise<AdminUserModel[]> {
    const index = createIndexRole(
      role
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_user by Role index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminUserByRole(
    role: AdminUserRole,
    data: AdminUserModel
  ): Promise<AdminUserModel[]> {
    const index = createIndexRole(
      role
    );

    const values = AdminUserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_user by Role index
   */
  async deleteAdminUserByRole(
    role: AdminUserRole
  ): Promise<void> {
    const index = createIndexRole(
      role
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_user by Status index
   * This function gets data by index.
   */
  async getAdminUserByStatus(
    status: AdminUserStatus,
  ): Promise<AdminUserModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_user by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminUserByStatus(
    status: AdminUserStatus,
    data: AdminUserModel
  ): Promise<AdminUserModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = AdminUserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_user by Status index
   */
  async deleteAdminUserByStatus(
    status: AdminUserStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_user by DataCreator index
   * This function gets data by index.
   */
  async getAdminUserByDataCreator(
    data_creator: string,
  ): Promise<AdminUserModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_user by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminUserByDataCreator(
    data_creator: string,
    data: AdminUserModel
  ): Promise<AdminUserModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = AdminUserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_user by DataCreator index
   */
  async deleteAdminUserByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get admin_user by DataUpdater index
   * This function gets data by index.
   */
  async getAdminUserByDataUpdater(
    data_updater: string,
  ): Promise<AdminUserModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) admin_user by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setAdminUserByDataUpdater(
    data_updater: string,
    data: AdminUserModel
  ): Promise<AdminUserModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = AdminUserModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete admin_user by DataUpdater index
   */
  async deleteAdminUserByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to AdminUserModel data array
   */
  private resultToData(values: Data[]): AdminUserModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return AdminUserModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as AdminUserModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized AdminUserModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is AdminUserModel => item !== null);
  }
}

/**
 * Convert AdminUserModel data to Value array
 */
function AdminUserModelToValues(data: AdminUserModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'username', type: DataType.string, defaultValue: '' },
    { key: 'email', type: DataType.string, defaultValue: '' },
    { key: 'password_hash', type: DataType.string, defaultValue: '' },
    { key: 'role', type: DataType.enumeration, defaultValue: 0 },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
    { key: 'last_login', type: DataType.string, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof AdminUserModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to AdminUserModel data
 */
function AdminUserModelFromValues(values: Value[]): AdminUserModel {
  const data: Partial<AdminUserModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'username':
        data.username = ParseValue(value, DataType.string) as string;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string;
        break;
      case 'password_hash':
        data.password_hash = ParseValue(value, DataType.string) as string;
        break;
      case 'role':
        data.role = ParseValue(value, DataType.enumeration) as AdminUserRole;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as AdminUserStatus;
        break;
      case 'last_login':
        data.last_login = ParseValue(value, DataType.string) as string | null;
        break;
    }
  }
  
  return data as AdminUserModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Username fields
 */
function createIndexUsername(
  username: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, username, 'username'),
  ];

  return {
    fields: ['username'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for Role fields
 */
function createIndexRole(
  role: AdminUserRole
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, role, 'role'),
  ];

  return {
    fields: ['role'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: AdminUserStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default AdminUserORM;