// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: blog_post.
// - Entity ID: 102019afbb8d7be714c86cd72d3ca5f88c8.
// - Entity Version: 102019b00c611587c8c865eed01327fc316.
// - Task ID: 69377e0a9be314c23511c3e0.
// - Task Root ID: 6935e04198d99bdd07fe5953.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";










/**
 * Interface for BlogPostModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface BlogPostModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  title: string;
  content: string;
  publish_date?: string | null;
  featured_image_url?: string | null;
  author_name: string;
  is_published: boolean;
  tags?: string[] | null;
}

/**
 * ORM class for BlogPost entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class BlogPostORM {
  private static instance: BlogPostORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019afbb8d7be714c86cd72d3ca5f88c8';
    this.entityName = 'blog_post';
    this.entityVersion = '102019b00c611587c8c865eed01327fc316';
    this.taskId = '69377e0a9be314c23511c3e0';
    this.taskRootId = '6935e04198d99bdd07fe5953';
  }

  /**
   * Get singleton instance of BlogPostORM
   */
  public static getInstance(): BlogPostORM {
    if (!BlogPostORM.instance) {
      BlogPostORM.instance = new BlogPostORM();
    }
    
    return BlogPostORM.instance;
  }

  /**
   * Get all BlogPost records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllBlogPost(): Promise<BlogPostModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new BlogPost record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertBlogPost(data: BlogPostModel[]): Promise<BlogPostModel[]> {
    const structured = data.map((item) => CreateData(BlogPostModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all BlogPost records
   */
  async purgeAllBlogPost(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List BlogPost records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listBlogPost(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[BlogPostModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get blog_post by Id index
   * This function gets data by index.
   */
  async getBlogPostById(
    id: string,
  ): Promise<BlogPostModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) blog_post by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBlogPostById(
    id: string,
    data: BlogPostModel
  ): Promise<BlogPostModel[]> {
    const index = createIndexId(
      id
    );

    const values = BlogPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete blog_post by Id index
   */
  async deleteBlogPostById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get blog_post by IsPublished index
   * This function gets data by index.
   */
  async getBlogPostByIsPublished(
    is_published: boolean,
  ): Promise<BlogPostModel[]> {
    const index = createIndexIsPublished(
      is_published
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) blog_post by IsPublished index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBlogPostByIsPublished(
    is_published: boolean,
    data: BlogPostModel
  ): Promise<BlogPostModel[]> {
    const index = createIndexIsPublished(
      is_published
    );

    const values = BlogPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete blog_post by IsPublished index
   */
  async deleteBlogPostByIsPublished(
    is_published: boolean
  ): Promise<void> {
    const index = createIndexIsPublished(
      is_published
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get blog_post by PublishDate index
   * This function gets data by index.
   */
  async getBlogPostByPublishDate(
    publish_date: string,
  ): Promise<BlogPostModel[]> {
    const index = createIndexPublishDate(
      publish_date
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) blog_post by PublishDate index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBlogPostByPublishDate(
    publish_date: string,
    data: BlogPostModel
  ): Promise<BlogPostModel[]> {
    const index = createIndexPublishDate(
      publish_date
    );

    const values = BlogPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete blog_post by PublishDate index
   */
  async deleteBlogPostByPublishDate(
    publish_date: string
  ): Promise<void> {
    const index = createIndexPublishDate(
      publish_date
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get blog_post by DataCreator index
   * This function gets data by index.
   */
  async getBlogPostByDataCreator(
    data_creator: string,
  ): Promise<BlogPostModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) blog_post by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBlogPostByDataCreator(
    data_creator: string,
    data: BlogPostModel
  ): Promise<BlogPostModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = BlogPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete blog_post by DataCreator index
   */
  async deleteBlogPostByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get blog_post by DataUpdater index
   * This function gets data by index.
   */
  async getBlogPostByDataUpdater(
    data_updater: string,
  ): Promise<BlogPostModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) blog_post by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setBlogPostByDataUpdater(
    data_updater: string,
    data: BlogPostModel
  ): Promise<BlogPostModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = BlogPostModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete blog_post by DataUpdater index
   */
  async deleteBlogPostByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to BlogPostModel data array
   */
  private resultToData(values: Data[]): BlogPostModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return BlogPostModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as BlogPostModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized BlogPostModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is BlogPostModel => item !== null);
  }
}

/**
 * Convert BlogPostModel data to Value array
 */
function BlogPostModelToValues(data: BlogPostModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'content', type: DataType.string, defaultValue: '' },
    { key: 'publish_date', type: DataType.string, defaultValue: null },
    { key: 'featured_image_url', type: DataType.string, defaultValue: null },
    { key: 'author_name', type: DataType.string, defaultValue: '' },
    { key: 'is_published', type: DataType.boolean, defaultValue: false },
    { key: 'tags', type: DataType.array, defaultValue: null },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof BlogPostModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to BlogPostModel data
 */
function BlogPostModelFromValues(values: Value[]): BlogPostModel {
  const data: Partial<BlogPostModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'content':
        data.content = ParseValue(value, DataType.string) as string;
        break;
      case 'publish_date':
        data.publish_date = ParseValue(value, DataType.string) as string | null;
        break;
      case 'featured_image_url':
        data.featured_image_url = ParseValue(value, DataType.string) as string | null;
        break;
      case 'author_name':
        data.author_name = ParseValue(value, DataType.string) as string;
        break;
      case 'is_published':
        data.is_published = ParseValue(value, DataType.boolean) as boolean;
        break;
      case 'tags':
        data.tags = ParseValue(value, DataType.array) as string[] | null;
        break;
    }
  }
  
  return data as BlogPostModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for IsPublished fields
 */
function createIndexIsPublished(
  is_published: boolean
): Index {
  const values: Value[] = [
    CreateValue(DataType.boolean, is_published, 'is_published'),
  ];

  return {
    fields: ['is_published'],
    values
  };
}
/**
 * Create index for PublishDate fields
 */
function createIndexPublishDate(
  publish_date: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, publish_date, 'publish_date'),
  ];

  return {
    fields: ['publish_date'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default BlogPostORM;