// Code generated by raf using Material interface.
// - Namespace: 01987547fc6c72ecb453bd2736bd4ea0.
// - Entity Name: game_suggestion.
// - Entity ID: 102019afbb8d7be77bd9d53a62a92e385bd.
// - Entity Version: 102019b00c611587c8c865eed01327fc316.
// - Task ID: 69377e0a9be314c23511c3e0.
// - Task Root ID: 6935e04198d99bdd07fe5953.

import { DataType } from "./common";
import type { Value, Page, Index, Filter, Sort, Data } from "./common";
import { DataStoreClient, CreateData, CreateValue, ParseValue } from "./client";







/**
 * Enumeration for GameSuggestionStatus
 */
export enum GameSuggestionStatus {
  Unspecified = 0,
  New = 1,
  UnderReview = 2,
  Accepted = 3,
  Rejected = 4,
}



/**
 * Interface for GameSuggestionModel
 * `id`, `data_creator`, `data_updater`, `create_time`, `update_time` should not be set when INSERTING data since backend will fill it automatically.
 * `id` should keep the original value when setting (updating) data.
 * `data_creator` and `data_updater` are read-only strings (user id) representing the creator and updater of the data record.
 * `create_time` and `update_time` are read-only strings in the format of timestamp (10-digit).
 */
export interface GameSuggestionModel {
  id: string;
  data_creator: string;
  data_updater: string;
  create_time: string;
  update_time: string;
  title: string;
  description?: string | null;
  email?: string | null;
  status: GameSuggestionStatus;
}

/**
 * ORM class for GameSuggestion entity.
 * It uses Singleton pattern to prevent re-initialization.
 */
export class GameSuggestionORM {
  private static instance: GameSuggestionORM | null = null;
  protected client: DataStoreClient;
  protected namespace: string;
  protected entityId: string;
  protected entityName: string;
  protected entityVersion: string;
  protected taskId: string;
  protected taskRootId: string;

  private constructor() {
    this.client = DataStoreClient.getInstance();
    this.namespace = '01987547fc6c72ecb453bd2736bd4ea0';
    this.entityId = '102019afbb8d7be77bd9d53a62a92e385bd';
    this.entityName = 'game_suggestion';
    this.entityVersion = '102019b00c611587c8c865eed01327fc316';
    this.taskId = '69377e0a9be314c23511c3e0';
    this.taskRootId = '6935e04198d99bdd07fe5953';
  }

  /**
   * Get singleton instance of GameSuggestionORM
   */
  public static getInstance(): GameSuggestionORM {
    if (!GameSuggestionORM.instance) {
      GameSuggestionORM.instance = new GameSuggestionORM();
    }
    
    return GameSuggestionORM.instance;
  }

  /**
   * Get all GameSuggestion records
   * This returns all data without pagination.
   * To query data with page and filter conditions, use `list*()` instead.
   */
  async getAllGameSuggestion(): Promise<GameSuggestionModel[]> {
    const response = await this.client.all({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Insert (create) new GameSuggestion record(s)
   * DO NOT SET `id`, `data_creator`, `data_updater`, `create_time` and `update_time` since backend will fill it automatically.
   * It will respond the inserted record(s), with `id`, `data_creator`, `data_updater`, `create_time` and `update_time` filled by backend.
   */
  async insertGameSuggestion(data: GameSuggestionModel[]): Promise<GameSuggestionModel[]> {
    const structured = data.map((item) => CreateData(GameSuggestionModelToValues(item)));
    const response = await this.client.insert({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      batch: structured,
      format: {
        structured: true
      }
    });
    return this.resultToData(response.data?.values || []);
  }

  /**
   * Purge all GameSuggestion records
   */
  async purgeAllGameSuggestion(): Promise<void> {
    await this.client.purge({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      format: {
        structured: true
      }
    });
  }

  /**
   * List GameSuggestion records with filters
   * This function provides search capabilities like filtering, sorting, pagination.
   */
  async listGameSuggestion(filter?: Filter, sort?: Sort, paginate?: Page): Promise<[GameSuggestionModel[], Page]> {
    const response = await this.client.list({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      filter: filter,
      sort: sort,
      paginate: paginate,
      format: {
        structured: true
      }
    });
    return [this.resultToData(response.data?.values || []), response.data?.page || { number: 0, size: 0 }];
  }


  /**
   * Get game_suggestion by Id index
   * This function gets data by index.
   */
  async getGameSuggestionById(
    id: string,
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexId(
      id
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_suggestion by Id index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSuggestionById(
    id: string,
    data: GameSuggestionModel
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexId(
      id
    );

    const values = GameSuggestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_suggestion by Id index
   */
  async deleteGameSuggestionById(
    id: string
  ): Promise<void> {
    const index = createIndexId(
      id
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_suggestion by Status index
   * This function gets data by index.
   */
  async getGameSuggestionByStatus(
    status: GameSuggestionStatus,
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexStatus(
      status
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_suggestion by Status index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSuggestionByStatus(
    status: GameSuggestionStatus,
    data: GameSuggestionModel
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexStatus(
      status
    );

    const values = GameSuggestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_suggestion by Status index
   */
  async deleteGameSuggestionByStatus(
    status: GameSuggestionStatus
  ): Promise<void> {
    const index = createIndexStatus(
      status
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_suggestion by DataCreator index
   * This function gets data by index.
   */
  async getGameSuggestionByDataCreator(
    data_creator: string,
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_suggestion by DataCreator index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSuggestionByDataCreator(
    data_creator: string,
    data: GameSuggestionModel
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexDataCreator(
      data_creator
    );

    const values = GameSuggestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_suggestion by DataCreator index
   */
  async deleteGameSuggestionByDataCreator(
    data_creator: string
  ): Promise<void> {
    const index = createIndexDataCreator(
      data_creator
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_suggestion by Email index
   * This function gets data by index.
   */
  async getGameSuggestionByEmail(
    email: string,
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexEmail(
      email
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_suggestion by Email index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSuggestionByEmail(
    email: string,
    data: GameSuggestionModel
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexEmail(
      email
    );

    const values = GameSuggestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_suggestion by Email index
   */
  async deleteGameSuggestionByEmail(
    email: string
  ): Promise<void> {
    const index = createIndexEmail(
      email
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }
  /**
   * Get game_suggestion by DataUpdater index
   * This function gets data by index.
   */
  async getGameSuggestionByDataUpdater(
    data_updater: string,
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const response = await this.client.get({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Set (update) game_suggestion by DataUpdater index
   * This function replaces data, so the data must be complete.
   * Must keep `id`, `data_creator`, `create_time` unchanged as original data (as fetched).
   * DO NOT SET `data_updater` and `update_time` since backend will fill it automatically.
   * It will respond the set record, with `data_updater` and `update_time` filled by backend.
   */
  async setGameSuggestionByDataUpdater(
    data_updater: string,
    data: GameSuggestionModel
  ): Promise<GameSuggestionModel[]> {
    const index = createIndexDataUpdater(
      data_updater
    );

    const values = GameSuggestionModelToValues(data);
    const structuredData = CreateData(values);

    const response = await this.client.set({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      data: structuredData,
      format: {
        structured: true
      }
    });

    return this.resultToData(response.data?.values || []);
  }

  /**
   * Delete game_suggestion by DataUpdater index
   */
  async deleteGameSuggestionByDataUpdater(
    data_updater: string
  ): Promise<void> {
    const index = createIndexDataUpdater(
      data_updater
    );

    await this.client.delete({
      id: this.entityId,
      namespace: this.namespace,
      name: this.entityName,
      version: this.entityVersion,
      task: this.taskId,
      index: index,
      format: {
        structured: true
      }
    });
  }

  /**
   * Convert result data to GameSuggestionModel data array
   */
  private resultToData(values: Data[]): GameSuggestionModel[] {
    return values.map((item: Data) => {
      if (item.structured && item.structured.length > 0) {
        return GameSuggestionModelFromValues(item.structured);
      }

      if (item.serialized) {
        try {
          const parsedData = JSON.parse(item.serialized) as GameSuggestionModel;
          return parsedData;
        } catch (error) {
          console.error('Error parsing serialized GameSuggestionModel data: ', error, item.serialized);
          return null;
        }
      }

      return null;
    }).filter((item): item is GameSuggestionModel => item !== null);
  }
}

/**
 * Convert GameSuggestionModel data to Value array
 */
function GameSuggestionModelToValues(data: GameSuggestionModel): Value[] {
  const fieldMappings = [
    { key: 'id', type: DataType.string, defaultValue: '' },
    { key: 'data_creator', type: DataType.string, defaultValue: '' },
    { key: 'data_updater', type: DataType.string, defaultValue: '' },
    { key: 'create_time', type: DataType.string, defaultValue: '' },
    { key: 'update_time', type: DataType.string, defaultValue: '' },
    { key: 'title', type: DataType.string, defaultValue: '' },
    { key: 'description', type: DataType.string, defaultValue: null },
    { key: 'email', type: DataType.string, defaultValue: null },
    { key: 'status', type: DataType.enumeration, defaultValue: 0 },
  ];

  return fieldMappings.map(({ key, type, defaultValue }) => {
    const value = data[key as keyof GameSuggestionModel] ?? defaultValue;
    return CreateValue(type, value, key);
  });
}

/**
 * Convert Value array to GameSuggestionModel data
 */
function GameSuggestionModelFromValues(values: Value[]): GameSuggestionModel {
  const data: Partial<GameSuggestionModel> = {};
  
  for (const value of values) {
    if (!value.name) continue;
    
    switch (value.name) {
      case 'id':
        data.id = ParseValue(value, DataType.string) as string;
        break;
      case 'data_creator':
        data.data_creator = ParseValue(value, DataType.string) as string;
        break;
      case 'data_updater':
        data.data_updater = ParseValue(value, DataType.string) as string;
        break;
      case 'create_time':
        data.create_time = ParseValue(value, DataType.string) as string;
        break;
      case 'update_time':
        data.update_time = ParseValue(value, DataType.string) as string;
        break;
      case 'title':
        data.title = ParseValue(value, DataType.string) as string;
        break;
      case 'description':
        data.description = ParseValue(value, DataType.string) as string | null;
        break;
      case 'email':
        data.email = ParseValue(value, DataType.string) as string | null;
        break;
      case 'status':
        data.status = ParseValue(value, DataType.enumeration) as GameSuggestionStatus;
        break;
    }
  }
  
  return data as GameSuggestionModel;
}


/**
 * Create index for Id fields
 */
function createIndexId(
  id: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, id, 'id'),
  ];

  return {
    fields: ['id'],
    values
  };
}
/**
 * Create index for Status fields
 */
function createIndexStatus(
  status: GameSuggestionStatus
): Index {
  const values: Value[] = [
    CreateValue(DataType.enumeration, status, 'status'),
  ];

  return {
    fields: ['status'],
    values
  };
}
/**
 * Create index for DataCreator fields
 */
function createIndexDataCreator(
  data_creator: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_creator, 'data_creator'),
  ];

  return {
    fields: ['data_creator'],
    values
  };
}
/**
 * Create index for Email fields
 */
function createIndexEmail(
  email: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, email, 'email'),
  ];

  return {
    fields: ['email'],
    values
  };
}
/**
 * Create index for DataUpdater fields
 */
function createIndexDataUpdater(
  data_updater: string
): Index {
  const values: Value[] = [
    CreateValue(DataType.string, data_updater, 'data_updater'),
  ];

  return {
    fields: ['data_updater'],
    values
  };
}

export default GameSuggestionORM;