/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TermsImport } from './routes/terms'
import { Route as SupportImport } from './routes/support'
import { Route as SuggestionsImport } from './routes/suggestions'
import { Route as SignupImport } from './routes/signup'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as PressImport } from './routes/press'
import { Route as MyTicketsImport } from './routes/my-tickets'
import { Route as MySuggestionsImport } from './routes/my-suggestions'
import { Route as LoginImport } from './routes/login'
import { Route as GamesImport } from './routes/games'
import { Route as DevlogImport } from './routes/devlog'
import { Route as ContactImport } from './routes/contact'
import { Route as AdminImport } from './routes/admin'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as GamesGameIdImport } from './routes/games.$gameId'

// Create/Update Routes

const TermsRoute = TermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any)

const SupportRoute = SupportImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRoute,
} as any)

const SuggestionsRoute = SuggestionsImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const PressRoute = PressImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRoute,
} as any)

const MyTicketsRoute = MyTicketsImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRoute,
} as any)

const MySuggestionsRoute = MySuggestionsImport.update({
  id: '/my-suggestions',
  path: '/my-suggestions',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const GamesRoute = GamesImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRoute,
} as any)

const DevlogRoute = DevlogImport.update({
  id: '/devlog',
  path: '/devlog',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GamesGameIdRoute = GamesGameIdImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GamesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/devlog': {
      id: '/devlog'
      path: '/devlog'
      fullPath: '/devlog'
      preLoaderRoute: typeof DevlogImport
      parentRoute: typeof rootRoute
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/my-suggestions': {
      id: '/my-suggestions'
      path: '/my-suggestions'
      fullPath: '/my-suggestions'
      preLoaderRoute: typeof MySuggestionsImport
      parentRoute: typeof rootRoute
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsImport
      parentRoute: typeof rootRoute
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/suggestions': {
      id: '/suggestions'
      path: '/suggestions'
      fullPath: '/suggestions'
      preLoaderRoute: typeof SuggestionsImport
      parentRoute: typeof rootRoute
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsImport
      parentRoute: typeof rootRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdImport
      parentRoute: typeof GamesImport
    }
  }
}

// Create and export the route tree

interface GamesRouteChildren {
  GamesGameIdRoute: typeof GamesGameIdRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameIdRoute: GamesGameIdRoute,
}

const GamesRouteWithChildren = GamesRoute._addFileChildren(GamesRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/devlog': typeof DevlogRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/my-suggestions': typeof MySuggestionsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/suggestions': typeof SuggestionsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/games/$gameId': typeof GamesGameIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/devlog': typeof DevlogRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/my-suggestions': typeof MySuggestionsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/suggestions': typeof SuggestionsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/games/$gameId': typeof GamesGameIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/devlog': typeof DevlogRoute
  '/games': typeof GamesRouteWithChildren
  '/login': typeof LoginRoute
  '/my-suggestions': typeof MySuggestionsRoute
  '/my-tickets': typeof MyTicketsRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/suggestions': typeof SuggestionsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/games/$gameId': typeof GamesGameIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/devlog'
    | '/games'
    | '/login'
    | '/my-suggestions'
    | '/my-tickets'
    | '/press'
    | '/privacy'
    | '/signup'
    | '/suggestions'
    | '/support'
    | '/terms'
    | '/games/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/devlog'
    | '/games'
    | '/login'
    | '/my-suggestions'
    | '/my-tickets'
    | '/press'
    | '/privacy'
    | '/signup'
    | '/suggestions'
    | '/support'
    | '/terms'
    | '/games/$gameId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/devlog'
    | '/games'
    | '/login'
    | '/my-suggestions'
    | '/my-tickets'
    | '/press'
    | '/privacy'
    | '/signup'
    | '/suggestions'
    | '/support'
    | '/terms'
    | '/games/$gameId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DevlogRoute: typeof DevlogRoute
  GamesRoute: typeof GamesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MySuggestionsRoute: typeof MySuggestionsRoute
  MyTicketsRoute: typeof MyTicketsRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SuggestionsRoute: typeof SuggestionsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DevlogRoute: DevlogRoute,
  GamesRoute: GamesRouteWithChildren,
  LoginRoute: LoginRoute,
  MySuggestionsRoute: MySuggestionsRoute,
  MyTicketsRoute: MyTicketsRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SuggestionsRoute: SuggestionsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/admin",
        "/contact",
        "/devlog",
        "/games",
        "/login",
        "/my-suggestions",
        "/my-tickets",
        "/press",
        "/privacy",
        "/signup",
        "/suggestions",
        "/support",
        "/terms"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/devlog": {
      "filePath": "devlog.tsx"
    },
    "/games": {
      "filePath": "games.tsx",
      "children": [
        "/games/$gameId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/my-suggestions": {
      "filePath": "my-suggestions.tsx"
    },
    "/my-tickets": {
      "filePath": "my-tickets.tsx"
    },
    "/press": {
      "filePath": "press.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/suggestions": {
      "filePath": "suggestions.tsx"
    },
    "/support": {
      "filePath": "support.tsx"
    },
    "/terms": {
      "filePath": "terms.tsx"
    },
    "/games/$gameId": {
      "filePath": "games.$gameId.tsx",
      "parent": "/games"
    }
  }
}
ROUTE_MANIFEST_END */
